steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/elevated-server-275615
/demo-service:0.0.2", "--build-arg=JAR_FILE=target/*.jar", "."]
images: ["gcr.io/elevated-server-275615
/demo-service:0.0.2"]
