steps:
- name: 'gcr.io/elevated-server-275615/demo-service'
  args: [ 'build', '-t --network=cloudbuild', 'gcr.io/elevated-server-275615/demo-service', '.' ]
images:
- 'gcr.io/elevated-server-275615/demo-service'
